/* SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause) */
/*
 * Qualcomm apq8064 interconnect IDs
 *
 * Copyright (c) 2022 Wouter Franken <wouter.franken@mind.be>
 */

#ifndef __DT_BINDINGS_INTERCONNECT_QCOM_APQ8064_H
#define __DT_BINDINGS_INTERCONNECT_QCOM_APQ8064_H

#define AFAB_MAS_AMPSS_M0		0
#define AFAB_MAS_AMPSS_M1		1
#define AFAB_TO_MFAB			2
#define AFAB_TO_SFAB			3
#define AFAB_SLV_EBI_CH0		4
#define AFAB_SLV_EBI_CH1		5
#define AFAB_SLV_AMPSS_L2		6

#define MFAB_MAS_MDP_PORT0			0
#define MFAB_MAS_MDP_PORT1			1
#define MFAB_MAS_ROTATOR			2
#define MFAB_MAS_GRAPHICS_3D		3
#define MFAB_MAS_GRAPHICS_3D_PORT1	4
#define MFAB_MAS_JPEG_DEC			5
#define MFAB_MAS_VIDEO_CAP			6
#define MFAB_MAS_VIDEO_ENC			7
#define MFAB_MAS_VFE				8
#define MFAB_MAS_VPE				9
#define MFAB_MAS_JPEG_ENC			10
#define MFAB_MAS_VIDEO_DEC			11
#define MFAB_TO_AFAB				12
#define MFAB_SLV_MM_IMEM			13

#define SFAB_MAS_SPS			0
#define SFAB_MAS_ADM_PORT0		1
#define SFAB_MAS_ADM_PORT1		2
#define SFAB_MAS_LPASS_PROC		3
#define SFAB_MAS_GSS_NAV		4
#define SFAB_MAS_PCIE			5
#define SFAB_MAS_RIVA			6
#define SFAB_MAS_SATA			7
#define SFAB_MAS_CRYPTO			8
#define SFAB_MAS_LPASS			9
#define SFAB_MAS_MMSS_FPB		10
#define SFAB_MAS_ADM0_CI		11
#define SFAB_TO_AFAB			12
#define SFAB_TO_SYS_FPB			13
#define SFAB_TO_CPSS_FPB		14
#define SFAB_SLV_SPS			15
#define SFAB_SLV_SYSTEM_IMEM	16
#define SFAB_SLV_CORESIGHT		17
#define SFAB_SLV_PCIE			18
#define SFAB_SLV_CRYPTO			19
#define SFAB_SLV_RIVA			20
#define SFAB_SLV_SATA			21
#define SFAB_SLV_AMPSS			22
#define SFAB_SLV_GSS			23
#define SFAB_SLV_LPASS			24
#define SFAB_SLV_MMSS_FPB		25

#define SYS_FPB_MAS_SPDM			0
#define SYS_FPB_MAS_RPM				1
#define SYS_FPB_TO_SFAB				2
#define SYS_FPB_SLV_SPDM			3
#define SYS_FPB_SLV_RPM				4
#define SYS_FPB_SLV_RPM_MSG_RAM		5
#define SYS_FPB_SLV_MPM				6
#define SYS_FPB_SLV_PMIC1_SSBI1_A	7
#define SYS_FPB_SLV_PMIC1_SSBI1_B	8
#define SYS_FPB_SLV_PMIC1_SSBI1_C	9
#define SYS_FPB_SLV_PMIC2_SSBI2_A	10
#define SYS_FPB_SLV_PMIC2_SSBI2_B	11

#define CPSS_FPB_TO_SFAB			0
#define CPSS_FPB_SLV_GSBI1_UART		1
#define CPSS_FPB_SLV_GSBI2_UART		2
#define CPSS_FPB_SLV_GSBI3_UART		3
#define CPSS_FPB_SLV_GSBI4_UART		4
#define CPSS_FPB_SLV_GSBI5_UART		5
#define CPSS_FPB_SLV_GSBI6_UART		6
#define CPSS_FPB_SLV_GSBI7_UART		7
#define CPSS_FPB_SLV_GSBI8_UART		8
#define CPSS_FPB_SLV_GSBI9_UART		9
#define CPSS_FPB_SLV_GSBI10_UART	10
#define CPSS_FPB_SLV_GSBI11_UART	11
#define CPSS_FPB_SLV_GSBI12_UART	12
#define CPSS_FPB_SLV_GSBI1_QUP		13
#define CPSS_FPB_SLV_GSBI2_QUP		14
#define CPSS_FPB_SLV_GSBI3_QUP		15
#define CPSS_FPB_SLV_GSBI4_QUP		16
#define CPSS_FPB_SLV_GSBI5_QUP		17
#define CPSS_FPB_SLV_GSBI6_QUP		18
#define CPSS_FPB_SLV_GSBI7_QUP		19
#define CPSS_FPB_SLV_GSBI8_QUP		20
#define CPSS_FPB_SLV_GSBI9_QUP		21
#define CPSS_FPB_SLV_GSBI10_QUP		22
#define CPSS_FPB_SLV_GSBI11_QUP		23
#define CPSS_FPB_SLV_GSBI12_QUP		24
#define CPSS_FPB_SLV_EBI2_NAND		25
#define CPSS_FPB_SLV_EBI2_CS0		26
#define CPSS_FPB_SLV_EBI2_CS1		27
#define CPSS_FPB_SLV_EBI2_CS2		28
#define CPSS_FPB_SLV_EBI2_CS3		29
#define CPSS_FPB_SLV_EBI2_CS4		30
#define CPSS_FPB_SLV_EBI2_CS5		31
#define CPSS_FPB_SLV_USB_FS1		32
#define CPSS_FPB_SLV_USB_FS2		33
#define CPSS_FPB_SLV_TSIF			34
#define CPSS_FPB_SLV_MSM_TSSC		35
#define CPSS_FPB_SLV_MSM_PDM		36
#define CPSS_FPB_SLV_MSM_DIMEM		37
#define CPSS_FPB_SLV_MSM_TCSR		38
#define CPSS_FPB_SLV_MSM_PRNG		39

#endif
